config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'documentary_films/index'
  get 'documentary_films/create'
  get 'documentary_films/new'
  get 'series/index'
  get 'series/create'
  get 'series/new'
  get 'movies/index'
  get 'movies/create'
  get 'movies/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"

  #Agregando rutas para el método post
  post "movies/create" => "movies#create"
  post "series/create" => "series#create"
  post "documentary_films/create" => "documentary_films#create"

 # get "/formulario/respuestadocumentales", to: "documentaryfilms#index"
 # get "/formulariodocumentales", to: "documentaryfilms#new"
 # get "/formulario/respuestaseries", to: "series#index"
 # get "/formularioseries", to: "series#new"
 # get '/formulario/respuestapeliculas', to: "moviess#index"
 # get '/formulariopeliculas', to: "movies#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/documentaryfilm.rb
class Documentaryfilm < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_film = DocumentaryFilm.all
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_films_params)

    if @documentary_film.save
      redirect_to documentary_films_index_path
    else
      render :new
    end
  end

  def new #new queda asi porque acá está el formulario
  end

  def documentary_films_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movie = Movie.all
  end

  def create
    @movie = Movie.new(movies_params)

    if @movie.save
      redirect_to movies_index_path
    else
      render :new
    end
  end

  def new #new queda asi porque acá está el formulario
  end

  def movies_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @serie = Serie.all
  end

  def create
    @serie = Serie.new(series_params)

    if @serie.save
      redirect_to series_index_path
    else
      render :new
    end
  end

  def new #new queda asi porque acá está el formulario
  end

  def series_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentaryfilms_helper.rb
module DocumentaryfilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/create.html.erb
<h1>Documentaryfilms#create</h1>
<p>Find me in app/views/documentaryfilms/create.html.erb</p>

app/views/documentary_films/index.html.erb
<div class="container1">
    <h1>¡Muchas gracias por colaborar con nosotros y completar el formulario de Documentales! </h1>
    <h3> Nos ayudas un montón a seguir creciendo </h3>
</div>

<%= link_to "Completar fomurlario para series", series_new_path %> <br>
<%= link_to "Completar fomurlario para peliculas", movies_new_path %> <br>
<%= link_to "Completar fomurlario para documentales", documentary_films_new_path %> <br> <br>


<div class="container">
    <div class="row">
        <div class="col-4">
            <h3 class=titulo> Aportes de otros Usuarios </h3>

            <% @documentary_film.each do |x| %>
                <h2> <%= x.name %> </h2>
                <p> <%= x.synopsis %> </p>
                <p> <%= x.director %> </p>
            <% end %>

        </div>
        <div class="col-8">
            <%= image_tag '6.jpg', class: "img-fluid", alt:"imagendocumental", style: "width: 900px; height:500px; object-fit:cover; margin-bottom:40px; " %>
        </div>
    </div>
</div>

app/views/documentary_films/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <h1> Completa el formulario para Documentales</h1>

            <%= form_with url:'/documentary_films/create', model: @documentary_film, method: :post do |form| %>
            <div class="form-group mb-3">
                <%= form.label :name, "Nombre del documental", class: "form-label" %> <br>
                <%= form.text_field :name, name: "documentary_film[name]" %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.label :synopsis, "Escribe una pequeña sinopsis del documental", class: "form-label" %> <br>
                <%= form.text_area :synopsis, name: "documentary_film[synopsis]", rows: 5, cols:40 %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.label :director, "Mencional al o los directores del documental", class: "form-label" %> <br>
                <%= form.text_field :director, name: "documentary_film[director]" %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.submit "Enviar", class: "btn btn-primary" %> <br>
            </div>
            <% end %>
        </div>
        <div class="col-8">
            <%= image_tag '3.png', class: "img-fluid", alt:"imagendocumental", style: "width: 1100px; height:600px; object-fit:cover; margin-bottom:40px; " %>
        </div>
    </div>
</div>

app/views/documentaryfilms/index.html.erb
<div class="container1">
    <h1>¡Muchas gracias por colaborar con nosotros y completar el formulario de Documentales! </h1>
    <h3> Nos ayudas un montón a seguir creciendo </h3>
</div>

<%= link_to "Completar fomurlario para series", series_new_path %> <br>
<%= link_to "Completar fomurlario para peliculas", movies_new_path %> <br>
<%= link_to "Completar fomurlario para documentales", documentaryfilms_new_path %> <br> <br>


<div class="container">
    <div class="row">
        <div class="col-4">
            <h3 class=titulo> Aportes de otros Usuarios </h3>

            <% @documentaryfilm.each do |x| %>
                <h2> <%= x.name %> </h2>
                <p> <%= x.synopsis %> </p>
                <p> <%= x.director %> </p>
            <% end %>

        </div>
        <div class="col-8">
            <%= image_tag '6.jpg', class: "img-fluid", alt:"imagendocumental", style: "width: 900px; height:500px; object-fit:cover; margin-bottom:40px; " %>
        </div>
    </div>
</div>

app/views/documentaryfilms/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <h1> Completa el formulario para Documentales</h1>

            <%= form_with url:'/documentaryfilms/create', model: @documentaryfilm, method: :post do |form| %>
            <div class="form-group mb-3">
                <%= form.label :name, "Nombre del documental", class: "form-label" %> <br>
                <%= form.text_field :name, name: "documentaryfilm[name]" %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.label :synopsis, "Escribe una pequeña sinopsis del documental", class: "form-label" %> <br>
                <%= form.text_area :synopsis, name: "documentaryfilm[synopsis]", rows: 5, cols:40 %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.label :director, "Mencional al o los directores del documental", class: "form-label" %> <br>
                <%= form.text_field :director, name: "documentaryfilm[director]" %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.submit "Enviar", class: "btn btn-primary" %> <br>
            </div>
            <% end %>
        </div>
        <div class="col-8">
            <%= image_tag '3.png', class: "img-fluid", alt:"imagendocumental", style: "width: 1100px; height:600px; object-fit:cover; margin-bottom:40px; " %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>CinemaRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Pacifico&family=Playfair:wght@300&display=swap" rel="stylesheet">
</head>

<body>

  <nav class="navbar navbar-expand-lg fondonavbar">
    <div class="container-fluid textos">
      <a class="navbar-brand text-blue" href="#">Menú</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <!--<ul class="navbar-nav ms-auto me-5">-->
          <li class="nav-item">
            <%= link_to "Home", pages_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Películas", movies_new_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Series", series_new_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Documentales", documentary_films_new_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Resultados Películas", movies_index_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Resultados Series", series_index_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Resultados Documentales", documentary_films_index_path, class:"nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-5">
    <%= yield %>
  </div>

  <footer class="footer">
    <div class="text-center p-3">
      © 2023 Copyright:
      <section class="text-dark">
        Todos los derechos reservados
      </section>
      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-twitter"></i></a>

      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-google"></i></a>
      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-instagram"></i></a>

      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-facebook-f"></i></a>

      <a class="btn btn-link btn-floating btn-lg text-dark m-1" href="#!" role="button" data-mdb-ripple-color="dark"><i
          class="fab fa-github"></i></a>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"> </script>
</body>

</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<div class="container1">
    <h1>¡Muchas gracias por colaborar con nosotros y completar el formulario de películas! </h1>
    <h3> Nos ayudas un montón a seguir creciendo </h3>
</div>

<%= link_to "Completar otro fomurlario para series", series_new_path %> <br>
<%= link_to "Completar otro fomurlario para peliculas", movies_new_path %> <br>
<%= link_to "Completar otro fomurlario para documentales", documentary_films_new_path %> <br> <br>


<div class="container">
    <div class="row">
        <div class="col-4">
            <h3 class=titulo> Aportes de otros Usuarios </h3>

            <% @movie.each do |x| %>
                <h2> <%= x.name %> </h2>
                <p> <%= x.synopsis %> </p>
                <p> <%= x.director %> </p>
            <% end %>

        </div>
        <div class="col-8">
            <%= image_tag '4.jpeg', class: "img-fluid", alt:"imagendocumental", style: "width: 900px; height:500px; object-fit:cover; margin-bottom:40px; " %>
        </div>
    </div>
</div>

app/views/movies/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <h1> Completa el formulario para Películas</h1>

            <%= form_with url:'/movies/create', model: @movie, method: :post do |form| %>
            <div class="form-group mb-3">
                <%= form.label :name, "Nombre de la película", class: "form-label" %> <br>
                <%= form.text_field :name, name: "movie[name]" %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.label :synopsis, "Escribe una pequeña sinopsis de la película", class: "form-label" %> <br>
                <%= form.text_area :synopsis, name: "movie[synopsis]", rows: 5, cols:40 %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.label :director, "Mencional al o los directores de la película", class: "form-label" %> <br>
                <%= form.text_field :director, name: "movie[director]" %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.submit "Enviar", class: "btn btn-primary" %> <br>
            </div>
        <% end %>
        </div>
        <div class="col-8">
        <%= image_tag '1.jpeg', class: "img-fluid", alt:"imagenpelicula", style: "width: 1100px; height:600px; object-fit:cover; margin-bottom:40px; " %>
        </div>
    </div>
</div>

app/views/pages/index.html.erb
<div class="container1">
    <h1>Ayúdanos a recopilar información</h1>
    <p> SE PARTE DE NUESTRA PÁGINA </p>
</div>

<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag '1.jpeg', class:"d-block w-200", alt:"peliculas" %>
    </div>
    <div class="carousel-item">
      <%= image_tag '2.jpeg', class:"d-block w-200", alt:"series" %>
    </div>
    <div class="carousel-item">
      <%= image_tag '3.png', class:"d-block w-200", alt:"documentales" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<div class="container1">
    <h1>¡Muchas gracias por colaborar con nosotros y completar el formulario de series! </h1>
    <h3> Nos ayudas un montón a seguir creciendo </h3>
</div>

<%= link_to "Completar otro fomurlario para series", series_new_path %> <br>
<%= link_to "Completar otro fomurlario para peliculas", movies_new_path %> <br>
<%= link_to "Completar otro fomurlario para documentales", documentary_films_new_path %> <br> <br>


<div class="container">
    <div class="row">
        <div class="col-4">
            <h3 class=titulo> Aportes de otros Usuarios </h3>

            <% @serie.each do |x| %>
                <h2> <%= x.name %> </h2>
                <p> <%= x.synopsis %> </p>
                <p> <%= x.director %> </p>
            <% end %>

        </div>
        <div class="col-8">
            <%= image_tag '5.jpeg', class: "img-fluid", alt:"imagendocumental", style: "width: 900px; height:500px; object-fit:cover; margin-bottom:40px; " %>
        </div>
    </div>
</div>

app/views/series/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <h1> Completa el formulario para Series</h1>

            <%= form_with url:'/series/create', model: @serie, method: :post do |form| %>
            <div class="form-group mb-3">
                <%= form.label :name, "Nombre de la serie", class: "form-label" %> <br>
                <%= form.text_field :name, name: "serie[name]" %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.label :synopsis, "Escribe una pequeña sinopsis de la serie", class: "form-label" %> <br>
                <%= form.text_area :synopsis, name: "serie[synopsis]", rows: 5, cols:40 %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.label :director, "Mencional al o los directores de la serie", class: "form-label" %> <br>
                <%= form.text_field :director, name: "serie[director]" %> <br>
            </div>
            <div class="form-group mb-3">
                <%= form.submit "Enviar", class: "btn btn-primary" %> <br>
            </div>
        <% end %>
        </div>
        <div class="col-8">
        <%= image_tag '2.jpeg', class: "img-fluid", alt:"imagenseries", style: "width: 1000px; height:600px; object-fit:cover; margin-bottom:40px; " %>
        </div>
    </div>
</div>